import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
// import { ThemeProvider } from "@/components/theme-provider";
import MainContainer from "@/components/MainContsiner";
import { Toaster } from "@/components/ui/toaster";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html suppressHydrationWarning lang="en">
        <body
          data-theme="light"
          className={`${spaceGrotesk.className} antialiased text-foreground`}
        >
          <div className="w-screen h-screen background-radial-gradient fixed top-0 left-0"></div>
          <div className="fixed w-screen h-screen top-0 left-0 backdrop-blur-md"></div>
          <Toaster />
          {/* <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          > */}
          <MainContainer>{children}</MainContainer>
          {/* </ThemeProvider> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
